#!/usr/bin/env bash
echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
make lint > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "****************************************************"
  echo "                 Detekt failed                      "
  echo " make fmt を実行するか、直接修正してからコミットしてください "
  echo "****************************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT
