#
# dependabot.ymlファイルの設定オプション
# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file
#

#
# package-ecosystem
#
# URL
# - https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
#
# 概要
# - パッケージマネージャーのパッケージマニフェストの場所
#   - モノレポでもなければ、ほとんど'/'
#

#
# directory
#
# URL
# - https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
#
# 概要
# - パッケージ管理用のマニフェストファイルの位置
#
#

#
# schedule.interval
#
# URL
# - https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday
#
# 概要
# - 更新チェックをする頻度
# - 曜日指定などもできる
#
---
version: 2
updates:
  #
  # gradle
  #
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'daily'

  #
  # github-actions
  #
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
