#
# yamllintの設定
#
# - Default configuration
#   - https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
#
---

extends: default

rules:
  line-length:
    max: 80
    level: warning  # default: error

#
# 無視するPATH
#
ignore: |
  src/test/resources/datasets/yml/
