#
# yamllintの設定
#
# - Default configuration
#   - https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
#
---

extends: default

#
# 無視するPATH
#
ignore: |
  src/test/resources/datasets/yml/
