name: CI

on:
  push:

#
# actions/checkout
#
# URL
#   - https://github.com/actions/checkout
# 概要
#   - GITHUB_WORKSPACE配下のリポジトリをチェックアウト

#
# actions/setup-java
#
# URL
#   - https://github.com/actions/setup-java
# 概要
#   - JDK環境をセットアップ

#
# EnricoMi/publish-unit-test-result-action@v2
#
# URL
#   - https://github.com/EnricoMi/publish-unit-test-result-action
# 概要
#   - テスト結果ファイルを解析し、結果をGitHubで公開する
#   - JUnit XMLファイル形式をサポート

#
# paambaati/codeclimate-action
#
# URL
#   - https://github.com/paambaati/codeclimate-action
# 概要
#   - JacocoレポートをCodeClimateに送る

#
# actions/upload-pages-artifact
#
# URL
#   - https://github.com/actions/upload-pages-artifact
# 概要
#   - GitHub Pagesにデプロイできるアーティファクト(成果物)をパッケージングしてくれる
#   - アーティファクトの保存期間はデフォルトだと1日

jobs:
  ci-test:
    runs-on: ubuntu-latest
    #
    # GitHubActionsで利用可能な権限
    #
    # URL
    #   - https://docs.github.com/ja/actions/using-jobs/assigning-permissions-to-jobs
    #
    permissions:
      actions: none
      checks: write
      contents: read
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: write
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: '【mainブランチ】 make test.full && テストカバレッジレポートをCodeClimateに送る'
        if: github.ref == 'refs/heads/main'
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: make test.full
          coverageLocations: 'build/reports/jacoco/test/jacocoTestReport.xml:jacoco'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: ${{ github.workspace }}/src/main/kotlin
          TZ: Asia/Tokyo
      - name: '【mainブランチ以外】 make test'
        if: github.ref != 'refs/heads/main'
        run: make test
        env:
          TZ: Asia/Tokyo
      - name: テスト結果レポートをGitHub Actionsの上部に公開
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'JUnit5のテスト結果レポート'
          junit_files: 'build/test-results/**/*.xml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: テストカバレッジレポートを成果物(アーティファクト)にする
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/reports/jacoco/test/html/

  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: make lint
        run: make lint
