name: CI

on:
  push:

#
# actions/checkout
#
# URL
#   - https://github.com/actions/checkout
# 概要
#   - GITHUB_WORKSPACE配下のリポジトリをチェックアウト

#
# actions/setup-java
#
# URL
#   - https://github.com/actions/setup-java
# 概要
#   - JDK環境をセットアップ

#
# EnricoMi/publish-unit-test-result-action@v1
#
# URL
#   - https://github.com/EnricoMi/publish-unit-test-result-action
# 概要
#   - テスト結果ファイルを解析し、結果をGitHubで公開する
#   - JUnit XMLファイル形式をサポート

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: make test
        run: make test

      - name: テスト結果レポートをGitHub Actionsの上部に公開
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "JUnit5のテスト結果レポート"
          files: "build/test-results/**/*.xml"

  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: make lint
        run: make lint
